<?php

namespace StayForLong\HotelBeds;

use GuzzleHttp;

final class ServiceHotelsList
{
	public function __construct()
	{
		try {

		// Your API Key and secret
		$apiKey       = "cpn9qw3s6crpypkm4rx6943w";
		$sharedSecret = "yAjJCFPgVs";

		// Signature is generated by SHA256 (Api-Key + Shared Secret + Timestamp (in seconds))
		$signature = hash("sha256", $apiKey . $sharedSecret . time());

		// Example of call to the API
		$endpoint = "https://api.test.hotelbeds.com/hotel-api/0.2/status";

		$client = new GuzzleHttp\Client();


			$response = $client->request(
				"GET",
				$endpoint,
				[
					"Api-Key"     => $apiKey,
					"X-Signature" => $signature,
					"Accept"      => "application/xml"
				]
			);
			dd($response);


			/*if ($response->getStatusCode() != 200) {

				printf("%s returned '%s' (%d)\n",


					$response->getTransferInfo("effective_url"),

					$response->getInfo(),

					$response->getResponseCode()

				);

			} else {

				printf($response->getBody());

			}*/

		} catch (Exception $ex) {

			printf("Error while sending request, reason: %s\n", $ex->getMessage());

		}
	}
}